
server:
    port: 8080

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/zx_yqs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&rewriteBatchedStatements=true
    # 热更新devtools配置
    devtools:
        restart:
          enabled: true  #设置开启热部署
          additional-paths: src/main/java #重启目录
          exclude: WEB-INF/**

mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    # rmapper.xml文件中resultMap的type或者parameterType或者resultType会使用程序里定义的pojo的包名
    type-aliases-package: com.zx.yunqishe.trunkentity
    configuration:
      # 下划线转驼峰
      map-underscore-to-camel-case: true
      # 打印sql
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志logback
logging:
    config: classpath:logback-spring.xml

